# Generated by Django 5.0.6 on 2026-06-23 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Beach', 'Beach'), ('Mountain', 'Mountain'), ('Historical', 'Historical'), ('Religious', 'Religious'), ('Wildlife', 'Wildlife'), ('Adventure', 'Adventure')], max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=255)),
                ('entry_fee', models.CharField(blank=True, max_length=100)),
                ('opening_hours', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
